Docker setup
michaellisitsa/flydar pull request #2
Opened 2022-09-18 08:46 UTC by dmc-au

Got a container up and running so that dependency management should be smooth.

Instructions are in README_Docker.md

2022-09-18 08:47 UTC, dmc-au commented
Make sure you've got the docker daemon running before executing the commands in the README_Docker.md file

2022-09-22 05:24 UTC, michaellisitsa requested changes
good job getting this worked out. The database stuff is probably the key thing, if you don't have a sqlite file in your directory beforehand and all migrations been run, I don't think the app will work. And the whole point of docker is that you can just clone the repo, and it works. i.e. you don't need to install python locally as well to do the db creation / migration.

2022-09-22 05:24 UTC, michaellisitsa commented on Dockerfile
> +RUN apt-get install vim -y --no-install-recommends
Don't think you need Vim editor?

2022-09-22 05:24 UTC, michaellisitsa commented on Dockerfile
> +COPY . /opt/flydar
This adds the current sqlite file in your code repo into the docker container, together with any existing records. Instead, we should probably use a docker volume (via a docker-compose.yml). In the past I've created a postgres DB, and done the setup as per here https://github.com/michaellisitsa/expense_tracker/blob/0354eed5463653777f5731008043bd3152128f55/project/settings.py#L134-L144
and added the environment variables in the `docker-compose.yml` file:
https://github.com/michaellisitsa/expense_tracker/blob/0354eed5463653777f5731008043bd3152128f55/docker-compose.yml#L8-L11

It looks like I've probably followed the official docker django docs to get the above here https://docs.docker.com/samples/django/

2022-09-25 02:53 UTC, merged